=== Adrii-0906/Lenguaje-de-Marcas/BaseX/Examen/television.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="canales">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="canal" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="programacion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="programas" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="programa" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="duracion" type="xs:integer"/>
                                                                <xs:element name="titulo" type="xs:string"/>
                                                                <xs:element name="descripcion" type="xs:string"/>
                                                                <xs:element name="clasificacion" type="xs:integer"/>
                                                                <xs:element name="capitulo" type="xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="dia" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="anuncios" maxOccurs="3" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="anuncio">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="marca" type="xs:string"/>
                                                    <xs:element name="duracion" type="xs:integer"/>
                                                    <xs:element name="horario" type="xs:time"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nombre" type="xs:string"/>
                        <xs:attribute name="numero" type="integer"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</schema>

=== Adrii-0906/Lenguaje-de-Marcas/BaseX/Examen/television.xml
<?xml version="1.0" encoding="UTF-8" ?>
<canales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="television.xsd">
    <canal nombre="hola" numero="1">
        <programacion dia="Lunes">
            <programas>
                <programa>
                   <duracion>45</duracion>
                    <titulo>uyy</titulo>
                    <descripcion>jfkdsajkfjdklas</descripcion>
                    <clasificacion>3</clasificacion>
                    <capitulo>1</capitulo>
                </programa>
            </programas>
        </programacion>
        <anuncios>
            <anuncio>
                <marca>marca</marca>
                <duracion>3</duracion>
                <horario>2</horario>
            </anuncio>
        </anuncios>
        <programacion dia="Martes">
            <programas>
                <programa>
                    <duracion>45</duracion>
                    <titulo>uyy</titulo>
                    <descripcion>jfkdsajkfjdklas</descripcion>
                    <clasificacion>3</clasificacion>
                    <capitulo>1</capitulo>
                </programa>
            </programas>
        </programacion>
        <anuncios>
            <anuncio>
                <marca>marca</marca>
                <duracion>3</duracion>
                <horario>2</horario>
            </anuncio>
        </anuncios>
        <programacion dia="Miercoles">
            <programas>
                <programa>
                    <duracion>45</duracion>
                    <titulo>uyy</titulo>
                    <descripcion>jfkdsajkfjdklas</descripcion>
                    <clasificacion>3</clasificacion>
                    <capitulo>1</capitulo>
                </programa>
            </programas>
        </programacion>
        <anuncios>
            <anuncio>
                <marca>marca</marca>
                <duracion>3</duracion>
                <horario>2</horario>
            </anuncio>
        </anuncios>
        <programacion dia="Jueves">
            <programas>
                <programa>
                    <duracion>45</duracion>
                    <titulo>uyy</titulo>
                    <descripcion>jfkdsajkfjdklas</descripcion>
                    <clasificacion>3</clasificacion>
                    <capitulo>1</capitulo>
                </programa>
            </programas>
        </programacion>
        <anuncios>
            <anuncio>
                <marca>marca</marca>
                <duracion>3</duracion>
                <horario>2</horario>
            </anuncio>
        </anuncios>
        <programacion dia="Viernes">
            <programas>
                <programa>
                    <duracion>45</duracion>
                    <titulo>uyy</titulo>
                    <descripcion>jfkdsajkfjdklas</descripcion>
                    <clasificacion>3</clasificacion>
                    <capitulo>1</capitulo>
                </programa>
            </programas>
        </programacion>
        <anuncios>
            <anuncio>
                <marca>marca</marca>
                <duracion>3</duracion>
                <horario>2</horario>
            </anuncio>
        </anuncios>
        <programacion dia="Sabado">
            <programas>
                <programa>
                    <duracion>45</duracion>
                    <titulo>uyy</titulo>
                    <descripcion>jfkdsajkfjdklas</descripcion>
                    <clasificacion>3</clasificacion>
                    <capitulo>1</capitulo>
                </programa>
            </programas>
        </programacion>
        <anuncios>
            <anuncio>
                <marca>marca</marca>
                <duracion>3</duracion>
                <horario>2</horario>
            </anuncio>
        </anuncios>
        <programacion dia="Domingo">
            <programas>
                <programa>
                    <duracion>45</duracion>
                    <titulo>uyy</titulo>
                    <descripcion>jfkdsajkfjdklas</descripcion>
                    <clasificacion>3</clasificacion>
                    <capitulo>1</capitulo>
                </programa>
            </programas>
        </programacion>
        <anuncios>
            <anuncio>
                <marca>marca</marca>
                <duracion>3</duracion>
                <horario>2</horario>
            </anuncio>
        </anuncios>
    </canal>
</canales>
